local addonName,SpaUI = ...
local L = SpaUI.Localization

local function test(event,...)
    print(event,...)
end

SpaUI:RegisterEvent('QUEST_ACCEPTED',test)
SpaUI:RegisterEvent('QUEST_AUTOCOMPLETE',test)
SpaUI:RegisterEvent('QUEST_COMPLETE',test)
SpaUI:RegisterEvent('QUEST_DETAIL',test)
SpaUI:RegisterEvent('QUEST_LOG_CRITERIA_UPDATE',test)
-- SpaUI:RegisterEvent('QUEST_LOG_UPDATE',test)
SpaUI:RegisterEvent('QUEST_POI_UPDATE',test)
SpaUI:RegisterEvent('QUEST_REMOVED',test)
SpaUI:RegisterEvent('QUEST_TURNED_IN',test)
-- SpaUI:RegisterEvent('QUEST_WATCH_LIST_CHANGED',test)
SpaUI:RegisterEvent('QUEST_WATCH_UPDATE',test)
-- SpaUI:RegisterEvent('QUESTLINE_UPDATE',test)
SpaUI:RegisterEvent('TASK_PROGRESS_UPDATE',test)
SpaUI:RegisterEvent('TREASURE_PICKER_CACHE_FLUSH',test)
SpaUI:RegisterEvent('WAYPOINT_UPDATE',test)
SpaUI:RegisterEvent('WORLD_QUEST_COMPLETED_BY_SPELL',test)
SpaUI:RegisterEvent('QUEST_ACCEPT_CONFIRM',test)
SpaUI:RegisterEvent('QUEST_FINISHED',test)
SpaUI:RegisterEvent('QUEST_GREETING',test)
SpaUI:RegisterEvent('QUEST_ITEM_UPDATE',test)
SpaUI:RegisterEvent('QUEST_PROGRESS',test)
SpaUI:RegisterEvent('DYNAMIC_GOSSIP_POI_UPDATED',test)
SpaUI:RegisterEvent('GOSSIP_CLOSED',test)
SpaUI:RegisterEvent('GOSSIP_CONFIRM',test)
SpaUI:RegisterEvent('GOSSIP_CONFIRM_CANCEL',test)
SpaUI:RegisterEvent('GOSSIP_ENTER_CODE',test)
SpaUI:RegisterEvent('GOSSIP_OPTIONS_REFRESHED',test)
SpaUI:RegisterEvent('GOSSIP_SHOW',test)